FROM openfoam/openfoam5-graphical-apps 

USER root
ENV DEBIAN_FRONTEND noninteractive

# gcc+ etc
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential git \
    && apt-get clean \
    && rm -r /var/lib/apt/lists/*

# install miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
RUN rm Miniconda3-latest-Linux-x86_64.sh
ENV PATH="$HOME/miniconda/bin:$PATH"

# python libs
RUN conda install -y scipy numpy matplotlib statsmodels swig jupyter
RUN conda install -y pygmo --channel conda-forge
RUN conda clean -ya
RUN pip install nlopt pyDOE2 pygame box2d-py GPy pyfoam numpy-stl

# copy over the project
RUN git clone https://bitbucket.org/georgedeath/egreedy/ /egreedy

# compile the pitzdaily solvers
SHELL ["/bin/bash", "-c"]
RUN source /opt/openfoam5/etc/bashrc \
    && wmake /egreedy/egreedy/test_problems/Exeter_CFD_Problems/data/PitzDaily/solvers/calcPressureDifference
